Q3: Download the Dermatology data set from the UCI depositary, apply KNN and analyze the
performance. Display the confusion matrix and discuss it. Use 10-Fold Cross Validation and random train/test split (70%, 30%).
Note: There might be some missing/null values in the dataset. First clean the data and then
work on the algorithm.

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [10]:
df = pd.read_csv('/content/dermatology.data')

df.replace('?', np.nan, inplace=True)
df.head()

2  2.1  0  3  0.1  0.2  0.3  0.4  1  0.5  ...  0.19  0.20  3.2  0.21  0.22  0.23  1.1  0.24  55  2.3
0  3    3  3  2    1    0    0    0  1    1  ...     0     0    0     0     0     0    1     0   8    1
1  2    1  2  3    1    3    0    3  0    0  ...     0     2    3     2     0     0    2     3  26    3
2  2    2  2  0    0    0    0    0  3    2  ...     3     0    0     0     0     0    3     0  40    1
3  2    3  2  2    2    2    0    2  0    0  ...     2     3    2     3     0     0    2     3  45    3
4  2    3  2  0    0    0    0    0  0    0  ...     0     0    2     0     0     0    1     0  41    2

[5 rows x 35 columns]

In [11]:
print(df.isnull().sum())

# to impute missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
df = pd.DataFrame(imputer.fit_transform(df))

print(df.isnull().sum())

2       0
2.1     0
0       0
3       0
0.1     0
0.2     0
0.3     0
0.4     0
1       0
0.5     0
0.6     0
0.7     0
0.8     0
0.9     0
0.10    0
3.1     0
2.2     0
0.11    0
0.12    0
0.13    0
0.14    0
0.15    0
0.16    0
0.17    0
0.18    0
0.19    0
0.20    0
3.2     0
0.21    0
0.22    0
0.23    0
1.1     0
0.24    0
55      8
2.3     0
dtype: int64
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
dtype: int64


In [12]:
X = df.iloc[:, :-1]  # All columns except the last one
y = df.iloc[:, -1]   # The last column as target


In [18]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix\n", cm)

print("Classification Report: \n",classification_report(y_test, y_pred))

Accuracy: 0.8727272727272727
Confusion Matrix
 [[32  1  0  0  0  0]
 [ 0 11  0  1  1  0]
 [ 0  0 22  0  0  0]
 [ 1  5  0 12  0  0]
 [ 1  0  0  2 16  1]
 [ 0  1  0  0  0  3]]
Classification Report: 
               precision    recall  f1-score   support

         1.0       0.94      0.97      0.96        33
         2.0       0.61      0.85      0.71        13
         3.0       1.00      1.00      1.00        22
         4.0       0.80      0.67      0.73        18
         5.0       0.94      0.80      0.86        20
         6.0       0.75      0.75      0.75         4

    accuracy                           0.87       110
   macro avg       0.84      0.84      0.83       110
weighted avg       0.88      0.87      0.87       110



10-Fold Cross-Validation

In [21]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(knn, X, y, cv=10)
print("Cross validation scores:", scores)
print("Mean accuracy:", scores.mean())

Cross-validation scores: [0.89189189 0.83783784 0.81081081 0.86486486 0.91891892 0.86111111
 0.88888889 0.88888889 0.97222222 0.83333333]
Mean accuracy: 0.8768768768768769
